### ISSUE TITLE
DLQ詳細メッセージダイアログにて、Payloadの内容がダイアログからはみ出る

### ISSUE THREAD

**Issue by A-pZ** [tomoakimikami/spr-dlq-management-web#2]
緑枠を参照。

![dlq-message-preview](https://cloud.githubusercontent.com/assets/624806/19672297/26e716da-9ab0-11e6-8e62-2f00d55c25c9.png)

**Comment by tomoakimikami** [comment]
現象を再現させることが出来ませんでした。
当方が試した環境は

OS
Mac OS X El Capitan 10.11.6

ブラウザ
Google Chrome 54.0.2840.61 (64bit)
Safari 10.0

ですが、この環境では、コンテンツがダイアログからはみ出ることなく、ダイアログ自体が縦に伸びて表示されています。

**Comment by A-pZ** [comment]
もう一度確認しましたが、半角英数記号のみで書かれたテキストが一定長続くと改行しないため問題が発生しているようです。

``` css
.form-control-static {
  word-wrap:break-word; 
}
```

を追記すれば問題ないかと存じます。

**Comment by tomoakimikami** [comment]
再現条件をご提示いただき、ありがとうございます。
こちらでも再現できましたので、対応を進めます。もうしばし、お待ちください。

**Comment by tomoakimikami** [comment]
対応しておきました。ご確認ください。

**Comment by A-pZ** [comment]
対応まことにありがとうございました！

**Comment by tomoakimikami** [comment]
問題なさそうですので、クローズしますね。
